Repository ITU-BDSA2024-GROUP19/Chirp, pull requests merged in 2024-12, with the labels that each got.

#185 feature/local-runnable-image
  src/Chirp.Infrastructure/Authors/AuthorRepository.cs
  src/Chirp.Infrastructure/Cheeps/CheepRepository.cs
  src/Chirp.Infrastructure/External/IOptionalBlobServiceClient.cs
  src/Chirp.Web/Startup.cs
  test/Chirp.Infrastructure.Test/CheepRepositoryUnitTest.cs
Labels: bug, enhancement

#165 Feature/hide user info behind show button
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
Labels: enhancement

#199 Made it so a user needs to use a unique email.
  src/Chirp.Web/Startup.cs
  test/Chirp.Web.Test/Playwright_StatusTest.cs
Labels: bug
